version: "3"
services:

  pihole:
    image: pihole/pihole:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=pihole_pihole
        - traefik.http.routers.pihole.entrypoints=web
        - traefik.http.routers.pihole.rule=PathPrefix("/")
        - traefik.http.services.pihole.loadbalancer.server.port=80
        - traefik.http.services.pihole.loadbalancer.sticky=true
        - traefik.http.services.pihole.loadbalancer.sticky.cookie.name=StickyCookie
    volumes:
      - pihole:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    networks:
      - pihole

    environment:
      - TZ='Europe/Berlin'
      - WEBPASSWORD=<your-password>
      - FTL_CMD=debug
      - DNSMASQ_LISTENING=all
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8


  traefik:
    image: traefik:latest
    deploy:
      placement:
        constraints: [ node.role==manager ]
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --ping=true
      - --entrypoints.web.address=:80
      - --providers.docker.swarmmode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=pihole_pihole
      - --providers.docker.watch=true
    ports:
      - "80:80"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - default
      - pihole


volumes:
  pihole:
  pihole_dnsmasq:

networks:
  pihole: